apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container-registry
  namespace: container-registry
spec:
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
