---
- hosts: controller

  tasks:
  - name: Install Ansible Galaxy collections/roles
    community.general.ansible_galaxy_install:
      type: both
      requirements_file: "{{ playbook_dir }}/requirements.yml"