---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    name: registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
        name: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: volv
          mountPath: /var/lib/registry
          subPath: registry
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
spec:
  selector:
    app: registry
  type: LoadBalancer
  ports:
    - name: registry-port
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: registry
data:
  access-token: "ZG9wX3YxX2ZiMjg2N2IyOWRhM2VjYzNhODg1Mzc1YzkzMzJkZDY1NmM3NWNjZWZkNzMyMWUxZWQxNTkyMjVkMzZiNzVlNzY="
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer
  namespace: registry
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mjcaley@darkarctic.com
    privateKeySecretRef:
      name: registry-issuer
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-int-darkarctic-com
  namespace: registry
spec:
  secretName: registry-int-darkarctic-com-tls
  issuerRef:
    name: issuer
  dnsNames:
  - 'registry.int.darkarctic.com'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry
  namespace: registry
  annotations:
    external-dns.alpha.kubernetes.io/hostname: registry.int.darkarctic.com
  labels:
    name: registry
spec:
  rules:
  - host: registry.int.darkarctic.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: registry
            port:
              number: 5000
  tls:
  - hosts:
    - registry.int.darkarctic.com
    secretName: registry-int-darkarctic-com-tls