---
- hosts: k3s_cluster
  vars:
    k3s_release_version: stable
    k3s_install_hard_links: true
    k3s_become: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  roles:
  - role: xanmanning.k3s

  tasks:
  - name: Install kubernetes client
    ansible.builtin.apt:
      name: python3-kubernetes
      update_cache: true
    become: true
  