---
- hosts: k3s_cluster
  vars:
    k3s_release_version: stable
    k3s_install_hard_links: true
    k3s_become: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  roles:
  - role: xanmanning.k3s

  tasks:
  - name: Install kubernetes client
    ansible.builtin.apt:
      name: python3-kubernetes
      update_cache: true
    become: true
  
  - name: MetalLB
    kubernetes.core.k8s:
      state: present
      apply: true
      src: https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
  
  - name: MetalLB address pools
    kubernetes.core.k8s:
      state: present
      src: ./metallb.yml

  - name: Longhorn
    kubernetes.core.k8s:
      state: present
      apply: true
      src: https://raw.githubusercontent.com/longhorn/longhorn/v1.6.0/deploy/longhorn.yaml
  
  - name: Prometheus operator
    kubernetes.core.k8s:
      state: present
      apply: true
      server_side_apply:
        field_manager: ansible
      src: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml

  - name: Checkout prometheus-kube
    ansible.builtin.git:
      repo: 'https://github.com/prometheus-operator/kube-prometheus.git'
      dest: /srv/checkout
      version: release-0.22

  - name: Prometheus server
    kubernetes.core.k8s:
      state: present
      apply: true
      src: ./prometheus.yml
  
  - name: Cloud Native PostgreSQL
    kubernetes.core.k8s:
      state: present
      apply: true
      src: https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
