---
- hosts: k3s_cluster
  vars:
    kubeconfig: /etc/rancher/k3s/k3s.yaml

  tasks:
  - name: Wait for MetalLB address pool CRD
    kubernetes.core.k8s_info:
      api_version: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: l2advertisements.metallb.io
      wait: true
      wait_condition:
        type: Established
        status: "True"

  - name: Wait for MetalLB address pool CRD
    kubernetes.core.k8s_info:
      api_version: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ipaddresspools.metallb.io
      wait: true
      wait_condition:
        type: Established
        status: "True"

  - name: MetalLB address pools
    kubernetes.core.k8s:
      definition:
      - apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: ip-pool
          namespace: metallb-system
        spec:
          addresses:
          - 192.168.10.0/24
      - apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: ip-pool
          namespace: metallb-system
      kubeconfig: "{{ kubeconfig }}"
    run_once: true
