---
- hosts: k3s_cluster
  vars:
    k3s_release_version: stable
    k3s_install_hard_links: true
    k3s_become: true
  roles:
  - role: xanmanning.k3s

  tasks:
  - name: Install Helm
    ansible.builtin.shell: |
      curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      chmod 700 get_helm.sh
      ./get_helm.sh
    become: true

  - name: Install kubernetes client
    ansible.builtin.apt:
      name: python3-kubernetes
      update_cache: true
    become: true

  - name: Download upgrade controller manifest
    ansible.builtin.get_url:
      url: https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml
      dest: ~/system-upgrade-controller.yaml
      mode: '0664'

  - name: Install upgrade controller
    kubernetes.core.k8s:
      state: present
      src: ~/system-upgrade-controller.yaml
      kubeconfig: /etc/rancher/k3s/k3s.yaml

  - name: Add Longhorn repository
    kubernetes.core.helm_repository:
      repo_name: longhorn
      repo_url: https://charts.longhorn.io

  - name: Install Longhorn
    kubernetes.core.helm:
      name: longhorn
      chart_ref: longhorn/longhorn
      release_namespace: longhorn-system
      create_namespace: true
      kubeconfig: /etc/rancher/k3s/k3s.yaml
