---
- hosts: controller

  tasks:
  - name: Install Pip
    ansible.builtin.apt:
      name: python3-pip
      update_cache: true
    become: true

  - name: Install k3s role
    community.general.ansible_galaxy_install:
      type: role
      name: xanmanning.k3s
